version: "3"

volumes:
    node_data: {}

services:
    server:
        image: node:12.10.0-alpine
        container_name: nodejs
        expose:
            - 5000
        environment:
            - TOKEN_BOT=_____YOU_TOKEN_____
        restart: on-failure
        deploy:
            restart_policy:
                condition: on-failure
        ports:
            - 5000:5000
        volumes:
            - "./:/home/app/"
        command: sh -c "cd /home/app && npm install --save && npm run start"
